### ISSUE TITLE
5.0以下的测试过么？

### ISSUE THREAD

**Issue by sangsais** [matrixxun/ImmersiveDetailSample#1]
4.4.4的华为显示有问题嘞

**Comment by sangsais** [comment]
4.4.4的华为显示有问题嘞
![qq 20170726141617](https://user-images.githubusercontent.com/6415942/28607158-1622f2a8-720d-11e7-9db4-5eea0be01e09.jpg)

**Comment by matrixxun** [comment]
你好， 已修复5.0以下FAB的显示问题。
